version: "3.1"
services:
  nodejs:
    container_name: completo
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/work
    ports:
      - "3000:3000"
    command: "node app.js"