service: kibana

provider:
  name: google
  runtime: nodejs
  project: utilidades  
  credentials: ~/.gcloud/keyfile.json

plugins:
  - serverless-google-cloudfunctions
  
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  kibana-dashboard:
    handler: dashboard
    events:
      - http: path

  kibana-visualizes:
    handler: visualizes
    events:
      - http: path